Name: "de"; MessagesFile: compiler:Languages\German.isl;  LicenseFile:"license-de.rtf";
Name: "fr"; MessagesFile: compiler:Languages\French.isl;  LicenseFile:"license-fr.rtf";
Name: "it"; MessagesFile: compiler:Languages\Italian.isl; LicenseFile:"license-it.rtf";
Name: "es"; MessagesFile: compiler:Languages\Spanish.isl; LicenseFile:"license-es.rtf";
Name: "zh"; MessagesFile: compiler:Languages\ChineseSimplified.isl; LicenseFile:"license-en.rtf";
