fr.FileAssoc=Associations de fichiers:
fr.DescContext=Ajouter "InnoUnpacker" au menu contextuel des fichiers exe
fr.InnoUnpack=Ouvrez le programme d'installation &Inno Setup avec InnoUnpacker

de.FileAssoc=Dateizuordnungen:
de.DescContext=Füge "InnoUnpacker" zum Kontext-Menü für exe-Dateien hinzu
de.InnoUnpack=Öffne &Inno Setup Installer mit InnoUnpacker

it.FileAssoc=Associazione file:
it.DescContext=Aggiungi "InnoUnpacker" al menu contestuale dei file exe
it.InnoUnpack=Apri installer &Inno Setup con InnoUnpacker

es.FileAssoc=Asociaciones de fichero:
es.DescContext=Añadir "InnoUnpacker" al menú contextual de ficheros exe
es.InnoUnpack=Abre el instalador de &Inno Setup con InnoUnpacker

zh.FileAssoc=文件关联:
zh.DescContext=将 "InnoUnpacker" ”添加到exe文件的右键菜单中
zh.InnoUnpack=使用InnoUnpacker打开Inno Setup安装程序
